### PR TITLE
some code review

### PR DESCRIPTION
**Pull request by richardlehane**
Hi Ross
apologies tried to do this in small commits but got lazy and the last commit is pretty chunky.
Not perfect but is a bit cleaner and perhaps faster too. 

If you haven't seen this: http://blog.golang.org/go-slices-usage-and-internals already, I found it an invaluable guide to getting my head around golang slices.

### CODE REVIEW

**Comment by ross-spencer** [comment]
Thanks for taking an interest in the code Richard. I'll take a look as early as possible and start merging. With my first release done a lot of that was about experimenting and so I am happy to start improving on that now with these.

**Comment by richardlehane** [comment]
No worries. I'd like fewer wildcards in pronom and this tool is a useful weapon in that fight!

**Comment by ross-spencer** [comment]
We have quite the fight! https://gist.github.com/ross-spencer/c3fea3964ad66c337335

**Comment by richardlehane** [comment]
my bete noire is Scalable Vector Graphics Tiny (http://apps.nationalarchives.gov.uk/PRONOM/Format/proFormatSearch.aspx?status=detailReport&id=1191&strPageToDisplay=signatures)... for every XML file let's wait infinite amount of bytes before that opening svg tag, what a great idea (hope not one of yours!)

**Comment by ross-spencer** [comment]
Right era! But I don't think mine ;) 

I also spot that we haven't specified the optional double or single quotes inside the XML sequences and so that's half of all XML negated completely. 

It'll be useful to see the signature definition extended, but with that wildcard it's gonna slow XML ID up even more. 

If i get an opportunity next week when i should be able to look at this merge and some signatures I'll see if i can help and can source some SVG from here or the UKWA... and we help to develop a min/max offset.

**Comment by richardlehane** [comment]
OK - little more tinkering... occurred to me could just use bytes.Index rather than roll own contains func. I'll stop now :)

**Comment by ross-spencer** [comment]
Thanks for the help on this Richard. GitHub doesn't enable easy commit-by-commit merges and so I ended up working through each case more manually. As a learning exercise I wanted to develop my skills and understanding as I went, so I've incorporated (hopefully) most of your suggestions above. 

I'm now at peace with multiple return statements as well ^_^

There's a little of my personal style still visible in the code. I'm a little more verbose in places where I'll pay the cost of a variable in memory for a little clarity, e.g. defining the start and end of a window to copy into the buffer, is a good example.

Unit testing in Golang is a big thing I wanted to tick off in my learning as well so some of my function definitions have been changed to better support my current abilities with such testing. It is likely I can improve further, so this is just the first step. 

The release as I'm sure you will have seen is here: https://github.com/ross-spencer/bindist/releases/tag/v2.0.0-beta 

I'll close this pull request for now, but yep, acknowledge most of its content should be visible inside the new code base.

**Pull request closed without merging**
